config/routes.rb
Rails.application.routes.draw do

  #Contact us Page routes
  resources :contacts, only: [:new, :create]
  get '/contacts' => 'contacts#create', as: :create

  devise_for :authors
  root to: 'blog/posts#index'
 # get '/signup' => 'Signup#create_author', as: :create_author
 # get '/signup' => 'Signups#create_author'


  namespace :authors do
    get '/account' => 'accounts#edit', as: :account
    put '/info' => 'accounts#update_info', as: :info
    put '/change_password' => 'accounts#change_password', as: :change_password



    resources :posts do
      put 'published' => 'posts#publish', on: :member
      put 'unpublished' => 'posts#unpublish', on: :member
    end
  end

  scope module: 'blog' do
    get 'about' => 'pages#about', as: :about
    get 'posts' => 'posts#index', as: :posts
    get 'posts/:id' => 'posts#show', as: :post
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<div class="footer">
    <footer class="footer navbar-fixed-bottom">
      <div class="container">
        <nav>
          <div class="item">
            <p class="footer-copyright pull-left">© 2017-2018 ALSTER SA DE CV. All rights reserved.</p>
            <div class="icon pull-right">
              <%= link_to image_tag('/assets/facebook_30x30.png', :hspace => '5'),"https://www.facebook.com/pistismex" %>
              <%= link_to image_tag('/assets/twitter_30x30.png', :hspace => '5'),"https://twitter.com/pistismex" %>
              <%= link_to image_tag('/assets/instagram_30x30.png', :hspace => '5'),"https://www.instagram.com/pistismex/" %>
            </div>
          </div>
        </nav>
      </div>
    </footer>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-toggleable-md fixed-top  bg-inverse">
  <div class="container">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="/">
      <%= image_tag '/assets/logo.png' %>
    </a>
    <%= form_tag(posts_path, method: 'get', class: 'navbar-form') do %>
        <%= search_field_tag :search, nil, class: 'form-control',placeholder: 'Search here..'  %>
        <%= submit_tag "Submit", class: 'btn btn-default', :name => nil %>
    <% end %>
    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item ">
          <%= link_to 'Blog', root_path, class: "nav-link #{yield(:blog_active)}" %>
        </li>
        <li class="nav-item ">
          <%= link_to 'About', about_path, class: "nav-link #{yield(:about_active)}" %>
        </li>
        <li class="nav-item ">
          <%= link_to 'Contact', new_contact_path, class: "nav-link #{yield(:contact_active)}" %>
        </li>
        <li class="nav-item dropdown author-nav">
          <% if author_signed_in? %>
              <a class="nav-link dropdown-toggle <%= yield(:author) %>" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <!-- Development -->
                <!--%= image_tag current_author.avatar.url(:thumb) %-->
                <!--Production -->
                <%= image_tag "/public#{current_author.avatar.url(:thumb)}" %>
                <%= current_author.name %>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <%= link_to 'My Post', authors_posts_path, class: "dropdown-item " %>
                <br>
                <%= link_to 'Account', authors_account_path, class: "dropdown-item" %>
                <br>
                <%= link_to 'Log Out', destroy_author_session_path, method: :delete, class: "dropdown-item" %>
              </div>
          <% else %>
              <a class="nav-link dropdown-toggle <%= yield(:author) %>" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Author
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <%= link_to 'Sign In', authors_posts_path, class: "dropdown-item" %>
                <br>
                <%= link_to 'Sign Up', new_author_registration_path, class: "dropdown-item" %>
              </div>
          <% end %>
        </li>
        <li class="nav-item dropdown">
          <div class="dropdown-menu" aria-labelledby="dropdown01">
            <a class="dropdown-item" href=<%= link_to 'Blog', root_path, class: "nav-link #{yield(:blog_active)}" %>>Blog</a>
            <a class="dropdown-item" href=<%= link_to 'About', about_path, class: "nav-link #{yield(:about_active)}" %>>About</a>
            <a class="dropdown-item" href=<%= link_to 'Contact', new_contact_path, class: "nav-link #{yield(:contact_active)}" %>>Contact</a>
            <% if author_signed_in? %>
                <a class="dropdown-item" href=<%= link_to 'My Post', authors_posts_path, class: "nav-link #{yield(:author)}" %>>My Post</a>
                <a class="dropdown-item" href=<%= link_to 'Log Out', destroy_author_session_path, method: :delete, class: "nav-link" %>>Log Out</a>
                <a class="dropdown-item" href=<%= image_tag(current_author.avatar.url(:thumb)) %>></a>
            <% else %>
                <a class="dropdown-item" href=<%= link_to 'Sign In', authors_posts_path, class: "nav-link #{yield(:author)}" %>>Sign In</a>
                <a class="dropdown-item" href=<%= link_to 'Sign Up', new_author_registration_path, class: "dropdown-item" %>>Sign Up</a>
            <% end %>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_sidebar.html.erb
<div id="wrapper">
  <div id="upright">
    <div class='span2 sidebar'>
      <h4>All Post</h4>
      <% if @posts %>
          <% @posts.each do |post| %>
              <h5 class="headline smaller-font">
                <%= link_to post.title, post %>
              </h5>
          <% end %>
          <!--<h4>Most Read</h4>-->
      <% end %>
    </div>
  </div>
</div>